version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/store?schema=public
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    networks:
      - store-network
    command: >
      sh -c "npx prisma migrate deploy && node dist/main"

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=store
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - store-network
      
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - store-network

networks:
  store-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: